In [55]:
#Basic Imports For Dataset Manipulation
import pandas as pd

In [56]:
#1). Read CSV File
df=pd.read_csv('Combined_dataset.csv')
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [57]:
#2). a). Head values
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [58]:
#b). Tail Values
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [59]:
#c). Shape
df.shape

(1000, 24)

In [60]:
#d). Columns
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [61]:
#e). Data Types
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [62]:
#f). Information
df.info

<bound method DataFrame.info of      product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]>

In [63]:
#3). a).Check Missing Values
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [64]:
#b). Filling Missing Values
df['discount'] = df['discount'].fillna(df['discount'].mean())
df['what_customers_said'] = df['what_customers_said'].fillna("No Review")
df['seller_name'] = df['seller_name'].fillna("Unknown Seller")
df['videos'] = df['videos'].fillna("No Video")
df['seller_information'] = df['seller_information'].fillna("No Information")
df['variations'] = df['variations'].fillna("No Variations")

In [65]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [66]:
#4). Performance Of Basic Operations
#a). Select Columns

sample_data=df[['title','rating','discount','final_price','currency']]
sample_data.head()

            title  rating  discount  final_price currency
0     Lino Perros     3.8      58.0  "₹3,995.00"      INR
1  Tommy Hilfiger     4.5      35.0  "₹2,899.00"      INR
2           Lavie     4.4      65.0  "₹2,999.00"      INR
3          F Gear     4.4      52.0  "₹1,675.00"      INR
4       MYTRIDENT     4.7      17.0  "₹2,899.00"      INR

In [67]:
#b). Filter Rows
filtered_row=df[df['rating']>3.0]
filtered_row.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",No Information,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",No Information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No Information,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No Information,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,No Information,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [68]:
#5). Remove Duplicates
#Check
df.duplicated().sum()

np.int64(0)

In [69]:
#Remove
df=df.drop_duplicates()

In [70]:
# Convert initial_price to string
df['initial_price'] = df['initial_price'].astype(str)

# Remove ₹ and commas from initial price column
df['initial_price'] = df['initial_price'].str.replace('₹', '', regex=False)
df['initial_price'] = df['initial_price'].str.replace(',', '', regex=False)
df['initial_price'] = df['initial_price'].str.strip()

# Convert to numeric datatype
df['initial_price'] = pd.to_numeric(df['initial_price'], errors='coerce')

# Create Quantity column beacuse not there
df['Quantity'] = 1

# Create  column name total_amount
df['total_amount'] = df['initial_price'] * df['Quantity']

df[['title', 'initial_price', 'Quantity', 'total_amount']].head()

            title  initial_price  Quantity  total_amount
0     Lino Perros           3995         1          3995
1  Tommy Hilfiger           2899         1          2899
2           Lavie           2999         1          2999
3          F Gear           1675         1          1675
4       MYTRIDENT           2899         1          2899

In [71]:
# 7). Saved Cleaned Data New CSV file 
df.to_csv("cleaned_dataset.csv", index=False)

# Brief Summary

# Objective

The main goal of this project was to learn about Python and use the Pandas library to explore and clean an ecommerce dataset called "Combined_dataset.csv".

# Tasks Performed

1. Loading the Dataset:-

I loaded the "Combined_dataset.csv" dataset into a Pandas DataFrame using the read_csv function. This was the step in my project.

2. Exploring the Dataset:-

To understand the dataset I used functions.

- I used head to see the first 5 rows.
- I used tail to see the last 5 rows.
- I checked the shape to see how many rows and columns the dataset had.
- I looked at the columns to see all the column names.
- I checked the data types to see what kind of data was in each column.
- I used info to get all the information about the dataset.

3. Handling Missing Values:-

I found missing values using isnull. Then I filled in the missing values in the columns with the average value. For the text columns I filled in the missing values with a custom value that made sense.

4. Performing Basic Operations:-

I did some things with the data.
- I picked the columns that were important.
- I filtered out rows based on the price of the product.
- I showed some information about the products.

5. Removing Duplicate Data:-

I. Removed duplicate rows in the dataset using drop_duplicates. This helped make the data better.

6. Creating a Derived Column:-

I made a column called total_amount. To do this I multiplied the price by the Quantity.
Since the dataset did not have a Quantity column I made a custom one for this calculation.

7. Saving the Cleaned Dataset:-
After I finished cleaning and transforming the data I saved the cleaned dataset as a file called cleaned_dataset.csv.

# Technologies Used

- I used Python for this project.
- I used Pandas to work with the data.
- I used Jupyter Notebook to write and run my code.

# Conclusion
"This project taught me a lot, about data analysis and cleaning using Pandas. I learned how to work with datasets handle missing values find information make new columns and save cleaned data into a new CSV file. The ecommerce dataset "Combined_dataset.csv" was an example to practice on. I gained a lot of experience working with the Pandas library on this ecommerce dataset "Combined_dataset.csv"."